# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

""" Prompts from various sources."""

import numpy as np

PROMPTS = np.array([
    # Own.
    'a one-line drawing of a cow',
    'a husky',
    'two avocados',
    'trypophobia',
    'A transformer robot with legs and arms made out of vegetation and leaves, logo',
    'mouse, vitruvian man',
    "Helsinki Skyline with 'StyleGAN' written with fireworks on the sky.",
    # Reddit.
    'Traffic jam inside Home Depot',
    'Jesse Pinkman Christmas Album Cover',
    'album cover of a band named "Jesus and Devil"',
    'a husky dog jumping from the top of a skyscraper to another skyscraper',
    'Dogs with replacement Lego parts',
    'Fisher Price Guillotine',
    'Fire Hydrant takes selfies on top of the Himalaya',
    'Anakin Skywalker vacuuming the beach to remove sand',
    'Samuel L. Jackson is elected as the new Pope',
    # Twitter.
    'Biologically accurate anatomical description of a birthday cake, medical book, full page, quadrichromic',
    'dynamism of psychosis by Umberto Boccioni, oil on canvas',
    'Voldemort meets annoying orange',
    'Humanity is killed by artificial intelligence, by James Gurney, oil on canvas',
    'dog eating noodles',
    'a black hole donut, scientific illustration',
    'Garden gnomes riding pigeons with saddles, digital art',
    'A head of broccoli complaining about the weather',
    'A still of Kermit The Frog in WALL-E (2008)',
    'A still of Kermit The Frog in The Sopranos (2005)',
    'teddy bears working on new AI research on the moon in the 1980s',
    "A painting inspired in Banksy's art showing a human-machine interaction.",
    'A city on Mars',
    'Androids dreaming of electric sheep',
    'a wise cat meditating in the Himalayas searching for enlightenment',
    'A warm fireplace on top of a building, in an apocalyptic city, steampunk style.',
    'high speed rail on a bridge over a lake at dawn with a hundred lanterns floating outside matte painting by studio ghibli',
    'digital cat with colorful glitches',
    # DALL-E Mini.
    'a graphite sketch of gothic cathedral',
    'An armchair in the shape of a pikachu. An armchair imitating a pikachu',
    'A blue colored dog.',
    'underwater cathedral',
    'watercolor of the Eiffel tower on the moon',
    'double rainbow over a lake',
    'sunset over purple mountains',
    'painting of an oniric forest glade surrounded by tall trees',
    'painting of a forest full of elves and fairies',
    'a photo of the golden gate bridge',
    'a graphite sketch of a market in the Middle Ages',
    'a volcano erupting next to the golden gate bridge',
    'a graphite sketch of Elon Musk',
    'a graphite sketch of Eva Longoria',
    'a graphite sketch of Kim Jong-un',
    'illustration of an avocado armchair',
    'still life in the style of Kandinsky',
    'painting of an alien by Claude Monet',
    'the eye of sauron, oil painting',
    'the moon is a skull',
    'a drawing of the Statue of Liberty',
    'a cool robot',
    'rat wearing a crown',
    'an illustration of a baby cucumber with a mustache playing chess',
    'an astronaut riding a horse in a photorealistic style',
    'a propaganda poster for transhumanism',
    'a beautiful epic fantasy painting of a space elevator',
    'Pharaoh Darth Vader of Egypt',
    'Darth Vader',
    'among us by keith haring',
    'aerial view of the beach at night',
    'the representation of infinity',
    'lofi nuclear war to relax and study to',
    'The Eye of Sauron reading a newspaper',
    'Spherical giraffe',
    'Plague doctor onlyfans',
    'Darth Vader in Soviet space propaganda poster',
    'Egyptian wall painting of Daft Punk',
    'the eye of sauron',
    'a t-shirt of an avocado',
    'cartoon of a carrot with big eyes',
    'a mouse riding a tricycle while eating chocolate',
    # Imagen.
    'A pear cut into seven pieces arranged in a ring.',
    'A brain riding a rocketship heading towards the moon.',
    'A blue coloured pizza.',
    'A cube made of brick. A cube with the texture of brick.',
    'A couple of glasses are sitting on a table.',
    'Hovering cow abducting aliens.',
    'A bald eagle made of chocolate powder, mango, and whipped cream',
    'Android Mascot made from bamboo.',
    'A photo of a Shiba Inu dog with a backpack riding a bike. It is wearing sunglasses and a beach hat.',
    'Teddy bears swimming at the Olympics 400m Butterfly event.',
    'A cute corgi lives in a house made out of sushi.',
    'A white colored sandwich.',
    'A pink colored giraffe.',
    'A real life photography of super mario, 8k Ultra HD.',
    'Greek statue of a man tripping over a cat.',
    'McDonalds Church.',
    'Lego Arnold Schwarzenegger.',
    'A photo of a confused grizzly bear in calculus class.',
    'A church with stained glass windows depicting a hamburger and french fries.',
    'A medieval painting of the wifi not working.',
    'A magnifying glass over a page of a 1950s batman comic.',
    'A 1960s poster warning against climate change.',
    'A pyramid made of falafel with a partial solar eclipse in the background.',
    'Hyper-realistic photo of an abandoned industrial site during a storm.',
    'Illustration of a mouse using a mushroom as an umbrella.',
    'A shark in the desert.',
    'A wine glass on top of a dog',
    "A painting by Grant Wood of an astronaut couple, american gothic style.",
    "A tiger in a lab coat with a 1980s Miami vibe, turning a well oiled science content machine, digital art.",
    "Darth Vader playing with raccoon in Mars during sunset.",
    "A red colored car",
    # Parti.
    'A giant cobra snake made from corn',
    'A blue Porsche 356 parked in front of a yellow brick wall.',
    'The back of a violin',
    'A spaceship made of cardboard',
    'A photo of a panda made of water',
    'A panda making latte art.',
    'A map of the United States made out of sushi. It is on a table next to a glass of red wine.',
    'A photo of an astronaut riding a horse in the forest. There is a river in front of them with water lilies.',
    # DALL-E 2 (paper).
    'vibrant portrait painting of Salvador Dalí with a robotic half face',
    'panda mad scientist mixing sparkling chemicals, artstation',
    'a red cube on a blue cube',
    'a hedgehog using a calculator, illustration',
    'a close up of a handpalm with leaves growing from it',
    'a corgi’s head depicted as an explosion of a nebula',
    'a propaganda poster depicting a cat dressed as french emperor napoleon holding a piece of cheese',
    'a teddy bear on a skateboard in times square',
    'a dolphin in an astronaut suit on saturn, artstation',
    'a shiba inu wearing a beret and black turtleneck',
    # DALL-E 2 (website).
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'An expressive oil painting of a basketball player dunking, depicted as an explosion of a nebula',
    'A photo of a white fur monster standing in a purple room',
    'A blue orange sliced in half laying on a blue floor in front of a blue wall',
    'A computer from the 90s in the style of vaporwave',
    'A sea otter with a pearl earring" by Johannes Vermeer',
    'A centered explosion of colorful powder on a black background',
    '3D render of a pink balloon dog in a violet room',
    'A cat riding a motorcycle',
    'A pencil and watercolor drawing of a bright city in the future with flying cars',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'High quality photo of a monkey astronaut',
    'A 3D render of an astronaut walking in a green desert',
    'A futuristic neon lit cyborg face',
    'A bowl of soup that is also a portal to another dimension, digital art',
    # GLIDE.
    'a pixel art corgi pizza',
    'a high-quality oil painting of a psychedelic hamster dragon',
    'a futuristic city in synthwave style',
    'a stained glass window of a panda eating bamboo',
    'an illustration of albert einstein wearing a superhero costume',
    'a fog rolling into new york',
    'a painting of a fox in the style of starry night',
    'a crayon drawing of a space elevator',
    'robots meditating in a vipassana retreat',
    'a fall landscape with a small cottage next to a lake',
    'a surrealist dream-like oil painting by salvador dalı́ of a cat playing checkers',
    # VQ-GAN CLIP.
    'A colored pencil drawing of a waterfall',
    'the Tower of Babel by J.M.W. Turner',
    'an astronaut in the style of van Gogh',
    'an autogyro flying car, trending on artstation',
    'sketch of a 3D printer by Leonardo da Vinci',
    'the universal library trending on artstation',
    'a forest rendered in low poly',
    'the gateway between dreams trending on artstation',
    'An oil painting of The New York City Skyline by Natalia Goncharova',
    'a forest rendered in the Unreal Engine',
    # eDiff-I.
    'A 4k dslr photo of a cute lion cub floating in a bowl of honey.',
    'A photo of a duckling wearing a medieval soldier helmet and riding a skateboard.',
    'An origami of a monkey dressed as a monk riding a bike on a mountain.',
    'A photo of two cute teddy bears sitting on top of a grizzly bear in a beautiful forest. Highly detailed fantasy art, 4k, artstation',
    'An abstract cubism painting of a penguin working as a fruit vendor in a tropical village',
    'A photo of a lion and a panda competing in the Olympics swimming event.',
])

STYLES = np.array([
    # eDiff-I.
    'cubism painting',
    'oil painting',
    'pixel art',
    'Vincent van Gogh painting',
    'real photo',
    'Rembrandt painting',
    'graphite sketch',
    'Egyptian tomb hieroglyphics painting',
    'Hokusai painting',
    'Madhubani painting',
    'origami',
    'watercolor drawing',
    'vaporwave',
    'crayon drawing ',
    'trending on artstation',
    'low poly',
    '4k dslr photo, highly detailed',
    'one-line drawing',
    'steampunk',
    'disney',
    'pixar',
    # https://www.reddit.com/r/MediaSynthesis/comments/p5nw28/clip_vqgan_keyword_comparison_by_kingdomakrillic/
    '8k resolution',
    'pencil sketch',
    '8k 3D',
    'deviantart',
    'Unreal Engine',
    'concept art',
    'artstation HD',
    'anime',
    'chalk art',
    'Tilt shift',
    'Depth of field',
    'volumetric lighting',
    "child's drawing",
    'marble sculpture',
    'airbrush art',
    'flat shading',
    'ink drawing',
    '#film',
    'holographic',
    'psychedlic',
    'groovy',
    'movie poster',
    'made of beads and yarn',
    'made of crystal',
    'made of cardboard',
    'made of vines',
    'made of cheese',
    'made of mist',
    'made of wrought iron',
    'tattoo',
    'woodcut',
    'constructivism',
    'impressionism',
    'fauvism',
    'art deco',
    'da vinci',
    'Marvel comics',
    'Ukiyo-e',
    'vray tracing',
    'minimalist',
    'geometric',
    '2D game art',
    'Soviet propaganda',
    'dutch golden age',
])

DRAWBENCH = np.array([
    "A red colored car.",
    "A black colored car.",
    "A pink colored car.",
    "A black colored dog.",
    "A red colored dog.",
    "A blue colored dog.",
    "A green colored banana.",
    "A red colored banana.",
    "A black colored banana.",
    "A white colored sandwich.",
    "A black colored sandwich.",
    "An orange colored sandwich.",
    "A pink colored giraffe.",
    "A yellow colored giraffe.",
    "A brown colored giraffe.",
    "A red car and a white sheep.",
    "A blue bird and a brown bear.",
    "A green apple and a black backpack.",
    "A green cup and a blue cell phone.",
    "A yellow book and a red vase.",
    "A white car and a red sheep.",
    "A brown bird and a blue bear.",
    "A black apple and a green backpack.",
    "A blue cup and a green cell phone.",
    "A red book and a yellow vase.",
    "A horse riding an astronaut.",
    "A pizza cooking an oven.",
    "A bird scaring a scarecrow.",
    "A blue coloured pizza.",
    "Hovering cow abducting aliens.",
    "A panda making latte art.",
    "A shark in the desert.",
    "An elephant under the sea.",
    "Rainbow coloured penguin.",
    "A fish eating a pelican.",
    "One car on the street.",
    "Two cars on the street.",
    "Three cars on the street.",
    "Four cars on the street.",
    "Five cars on the street.",
    "One dog on the street.",
    "Two dogs on the street.",
    "Three dogs on the street.",
    "Four dogs on the street.",
    "Five dogs on the street.",
    "One cat and one dog sitting on the grass.",
    "One cat and two dogs sitting on the grass.",
    "One cat and three dogs sitting on the grass.",
    "Two cats and one dog sitting on the grass.",
    "Two cats and two dogs sitting on the grass.",
    "Two cats and three dogs sitting on the grass.",
    "Three cats and one dog sitting on the grass.",
    "Three cats and two dogs sitting on the grass.",
    "Three cats and three dogs sitting on the grass.",
    "A triangular purple flower pot. A purple flower pot in the shape of a triangle.",
    "A triangular orange picture frame. An orange picture frame in the shape of a triangle.",
    "A triangular pink stop sign. A pink stop sign in the shape of a triangle.",
    "A cube made of denim. A cube with the texture of denim.",
    "A sphere made of kitchen tile. A sphere with the texture of kitchen tile.",
    "A cube made of brick. A cube with the texture of brick.",
    "A collection of nail is sitting on a table.",
    "A single clock is sitting on a table.",
    "A couple of glasses are sitting on a table.",
    "An illustration of a large red elephant sitting on a small blue mouse.",
    "An illustration of a small green elephant standing behind a large red mouse.",
    "A small blue book sitting on a large red book.",
    "A stack of 3 plates. A blue plate is on the top, sitting on a blue plate. The blue plate is in the middle, sitting on a green plate. The green plate is on the bottom.",
    "A stack of 3 cubes. A red cube is on the top, sitting on a red cube. The red cube is in the middle, sitting on a green cube. The green cube is on the bottom.",
    "A stack of 3 books. A green book is on the top, sitting on a red book. The red book is in the middle, sitting on a blue book. The blue book is on the bottom.",
    "An emoji of a baby panda wearing a red hat, green gloves, red shirt, and green pants.",
    "An emoji of a baby panda wearing a red hat, blue gloves, green shirt, and blue pants.",
    "A fisheye lens view of a turtle sitting in a forest.",
    "A side view of an owl sitting in a field.",
    "A cross-section view of a brain.",
    "A vehicle composed of two wheels held in a frame one behind the other, propelled by pedals and steered with handlebars attached to the front wheel.",
    "A large motor vehicle carrying passengers by road, typically one serving the public on a fixed route and for a fare.",
    "A small vessel propelled on water by oars, sails, or an engine.",
    "A connection point by which firefighters can tap into a water supply.",
    "A machine next to a parking space in a street, into which the driver puts money so as to be authorized to park the vehicle for a particular length of time.",
    "A device consisting of a circular canopy of cloth on a folding metal frame supported by a central rod, used as protection against rain or sometimes sun.",
    "A separate seat for one person, typically with a back and four legs.",
    "An appliance or compartment which is artificially kept cool and used to store food and drink.",
    "A mechanical or electrical device for measuring time.",
    "An instrument used for cutting cloth, paper, and other thin material, consisting of two blades laid one on top of the other and fastened in the middle so as to allow them to be opened and closed by a thumb and finger inserted through rings on the end of their handles.",
    "A large plant-eating domesticated mammal with solid hoofs and a flowing mane and tail, used for riding, racing, and to carry and pull loads.",
    "A long curved fruit which grows in clusters and has soft pulpy flesh and yellow skin when ripe.",
    "A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.",
    "A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, nonretractable claws, and a barking, howling, or whining voice.",
    "An organ of soft nervous tissue contained in the skull of vertebrates, functioning as the coordinating center of sensation and intellectual and nervous activity.",
    "An American multinational technology company that focuses on artificial intelligence, search engine, online advertising, cloud computing, computer software, quantum computing, e-commerce, and consumer electronics.",
    "A large keyboard musical instrument with a wooden case enclosing a soundboard and metal strings, which are struck by hammers when the keys are depressed. The strings' vibration is stopped by dampers when the keys are released and can be regulated for length and volume by two or three pedals.",
    "A type of digital currency in which a record of transactions is maintained and new units of currency are generated by the computational solution of mathematical problems, and which operates independently of a central bank.",
    "A large thick-skinned semiaquatic African mammal, with massive jaws and large tusks.",
    "A machine resembling a human being and able to replicate certain human movements and functions automatically.",
    "Paying for a quarter-sized pizza with a pizza-sized quarter.",
    "An oil painting of a couple in formal evening wear going home get caught in a heavy downpour with no umbrellas.",
    "A grocery store refrigerator has pint cartons of milk on the top shelf, quart cartons on the middle shelf, and gallon plastic jugs on the bottom shelf.",
    "In late afternoon in January in New England, a man stands in the shadow of a maple tree.",
    "An elephant is behind a tree. You can see the trunk on one side and the back legs on the other.",
    "A tomato has been put on top of a pumpkin on a kitchen stool. There is a fork sticking into the pumpkin. The scene is viewed from above.",
    "A pear cut into seven pieces arranged in a ring.",
    "A donkey and an octopus are playing a game. The donkey is holding a rope on one end, the octopus is holding onto the other. The donkey holds the rope in its mouth. A cat is jumping over the rope.",
    "Supreme Court Justices play a baseball game with the FBI. The FBI is at bat, the justices are on the field.",
    "Abraham Lincoln touches his toes while George Washington does chin-ups. Lincoln is barefoot. Washington is wearing boots.",
    "Tcennis rpacket.",
    "Bzaseball galove.",
    "Rbefraigerator.",
    "Dininrg tablez.",
    "Pafrking metr.",
    "A smafml vessef epropoeilled on watvewr by ors, sauls, or han engie.",
    "A sjmall domesticated carnivorious mammnal with sof fuh,y a sthort sout, and retracwtablbe flaws. It iw widexly kept as a pet or for catchitng mic, ad many breeds zhlyde beefn develvoked.",
    "An instqrumemnt used for cutting cloth, paper, axdz othr thdin mteroial, consamistng of two blades lad one on tvopb of the other and fhastned in tle mixdqdjle so as to bllow them txo be pened and closed by thumb and fitngesr inserted tgrough rings on kthe end oc thei vatndlzes.",
    "A domesticated carnivvorous mzammal that typicbally hfaas a lons sfnout, an acxujte sense off osmell, noneetractaaln crlaws, anid xbarkring,y howlingu, or whining rvoiche.",
    "A ldarge keybord msical instroument lwith a woden case enmclosig a qsouvnkboajrd and mfgtal strivgf, which are strucrk b hammrs when the nels are depresdsmed.f lhe strsingsj' vibration ie stopped by damperds when the keys re released and can bce regulavewdd for lengh and vnolume y two or three pedalvs.",
    "A train on top of a surfboard.",
    "A wine glass on top of a dog.",
    "A bicycle on top of a boat.",
    "An umbrella on top of a spoon.",
    "A laptop on top of a teddy bear.",
    "A giraffe underneath a microwave.",
    "A donut underneath a toilet.",
    "A hair drier underneath a sheep.",
    "A tennis racket underneath a traffic light.",
    "A zebra underneath a broccoli.",
    "A banana on the left of an apple.",
    "A couch on the left of a chair.",
    "A car on the left of a bus.",
    "A cat on the left of a dog.",
    "A carrot on the left of a broccoli.",
    "A pizza on the right of a suitcase.",
    "A cat on the right of a tennis racket.",
    "A stop sign on the right of a refrigerator.",
    "A sheep to the right of a wine glass.",
    "A zebra to the right of a fire hydrant.",
    "Acersecomicke.",
    "Jentacular.",
    "Matutinal.",
    "Peristeronic.",
    "Artophagous.",
    "Backlotter.",
    "Octothorpe.",
    "A church with stained glass windows depicting a hamburger and french fries.",
    "Painting of the orange cat Otto von Garfield, Count of Bismarck-Schönhausen, Duke of Lauenburg, Minister-President of Prussia. Depicted wearing a Prussian Pickelhaube and eating his favorite meal - lasagna.",
    "A baby fennec sneezing onto a strawberry, detailed, macro, studio light, droplets, backlit ears.",
    "A photo of a confused grizzly bear in calculus class.",
    "An ancient Egyptian painting depicting an argument over whose turn it is to take out the trash.",
    "A fluffy baby sloth with a knitted hat trying to figure out a laptop, close up, highly detailed, studio lighting, screen reflecting in its eyes.",
    "A tiger in a lab coat with a 1980s Miami vibe, turning a well oiled science content machine, digital art.",
    "A 1960s yearbook photo with animals dressed as humans.",
    "Lego Arnold Schwarzenegger.",
    "A yellow and black bus cruising through the rainforest.",
    "A medieval painting of the wifi not working.",
    "An IT-guy trying to fix hardware of a PC tower is being tangled by the PC cables like Laokoon. Marble, copy after Hellenistic original from ca. 200 BC. Found in the Baths of Trajan, 1506.",
    "35mm macro shot a kitten licking a baby duck, studio lighting.",
    "McDonalds Church.",
    "Photo of an athlete cat explaining it's latest scandal at a press conference to journalists.",
    "Greek statue of a man tripping over a cat.",
    "An old photograph of a 1920s airship shaped like a pig, floating over a wheat field.",
    "Photo of a cat singing in a barbershop quartet.",
    "A painting by Grant Wood of an astronaut couple, american gothic style.",
    "An oil painting portrait of the regal Burger King posing with a Whopper.",
    "A keyboard made of water, the water is made of light, the light is turned off.",
    "Painting of Mona Lisa but the view is from behind of Mona Lisa.",
    "Hyper-realistic photo of an abandoned industrial site during a storm.",
    "A screenshot of an iOS app for ordering different types of milk.",
    "A real life photography of super mario, 8k Ultra HD.",
    "Colouring page of large cats climbing the eifel tower in a cyberpunk future.",
    "Photo of a mega Lego space station inside a kid's bedroom.",
    "A spider with a moustache bidding an equally gentlemanly grasshopper a good day during his walk to work.",
    "A photocopy of a photograph of a painting of a sculpture of a giraffe.",
    "A bridge connecting Europe and North America on the Atlantic Ocean, bird's eye view.",
    "A maglev train going vertically downward in high speed, New York Times photojournalism.",
    "A magnifying glass over a page of a 1950s batman comic.",
    "A car playing soccer, digital art.",
    "Darth Vader playing with raccoon in Mars during sunset.",
    "A 1960s poster warning against climate change.",
    "Illustration of a mouse using a mushroom as an umbrella.",
    "A realistic photo of a Pomeranian dressed up like a 1980s professional wrestler with neon green and neon orange face paint and bright green wrestling tights with bright orange boots.",
    "A pyramid made of falafel with a partial solar eclipse in the background.",
    "A storefront with 'Hello World' written on it.",
    "A storefront with 'Diffusion' written on it.",
    "A storefront with 'Text to Image' written on it.",
    "A storefront with 'NeurIPS' written on it.",
    "A storefront with 'Deep Learning' written on it.",
    "A storefront with 'Google Brain Toronto' written on it.",
    "A storefront with 'Google Research Pizza Cafe' written on it.",
    "A sign that says 'Hello World'.",
    "A sign that says 'Diffusion'.",
    "A sign that says 'Text to Image'.",
    "A sign that says 'NeurIPS'.",
    "A sign that says 'Deep Learning'.",
    "A sign that says 'Google Brain Toronto'.",
    "A sign that says 'Google Research Pizza Cafe'.",
    "New York Skyline with 'Hello World' written with fireworks on the sky.",
    "New York Skyline with 'Diffusion' written with fireworks on the sky.",
    "New York Skyline with 'Text to Image' written with fireworks on the sky.",
    "New York Skyline with 'NeurIPS' written with fireworks on the sky.",
    "New York Skyline with 'Deep Learning' written with fireworks on the sky.",
    "New York Skyline with 'Google Brain Toronto' written with fireworks on the sky.",
    "New York Skyline with 'Google Research Pizza Cafe' written with fireworks on the sky.",
])

PROMPTS_TRAINING = np.array([
    'a graphite sketch of elon musk',
    'sunset over purple mountains',
    'a medieval painting of the wifi not working',
    'watercolor of the Eiffel tower on the moon',
    'panda mad scientist mixing sparkling chemicals, artstation',
    'a high-quality oil painting of a psychedelic hamster dragon',
    'a red cube on a blue cube',
    'a pink colored giraffe',
    'a dolphin in an astronaut suit on saturn, artstation',
])
